import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import { Nunito } from "next/font/google"
import "./globals.css"
import StoreProvider from "./components/providers/StoreProvider"
export const nunito = Nunito({
    subsets: ["latin", "cyrillic"],
    variable: "--font-nunito"
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
}

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={`${nunito.variable} ${nunito.className} antialiased min-h-max`}>
                <StoreProvider>{children}</StoreProvider>
            </body>
        </html>
    )
}
