import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import { Nunito } from "next/font/google"
import "./globals.css"
import { Toaster } from "react-hot-toast"
import ToasterProvider from "./components/providers/ToasterProvider"
export const nunito = Nunito({
    subsets: ["latin", "cyrillic"], // Подключаем кириллицу,   // Выбираем нужные веса (Regular, Semi-Bold, Bold)             // Текст виден сразу (сначала системным шрифтом)
    variable: "--font-nunito" // CSS-переменная для Tailwind или CSS-модулей
})
const geistSans = Geist({
    variable: "--font-nunito",
    subsets: ["latin"]
})

const geistMono = Geist_Mono({
    variable: "--font-nunito",
    subsets: ["latin"]
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
}

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={`${nunito.variable} ${nunito.className} antialiased min-h-max`}>{children}</body>
        </html>
    )
}
